### ISSUE TITLE
Failed to process Telegram update on Polls Updates

### ISSUE THREAD

**Issue by hamidqp** [badfarm/zanzara#11]
When I use the poll that created by bot get this on Logs : 

```
Failed to process Telegram update , reason: TypeError: Return value of Zanzara\Telegram\Type\Update::getUpdateType() must be of the type string, null returned in /home/xxx/bots/ChannelTest/ven
dor/badfarm/zanzara/src/Zanzara/Telegram/Type/Update.php:323
Stack trace:
#0 /home/xxx/bots/ChannelTest/vendor/badfarm/zanzara/src/Zanzara/Listener/ListenerResolver.php(36): Zanzara\Telegram\Type\Update->getUpdateType()
#1 /home/xxx/bots/ChannelTest/vendor/badfarm/zanzara/src/Zanzara/Zanzara.php(269): Zanzara\Listener\ListenerResolver->resolve()
#2 /home/xxx/bots/ChannelTest/vendor/badfarm/zanzara/src/Zanzara/Zanzara.php(245): Zanzara\Zanzara->processUpdate()
#3 /home/xxx/bots/ChannelTest/vendor/react/promise/src/FulfilledPromise.php(28): Zanzara\Zanzara->Zanzara\{closure}()
#4 /home/xxx/bots/ChannelTest/vendor/react/promise/src/Promise.php(134): React\Promise\FulfilledPromise->then()
#5 /home/xxx/bots/ChannelTest/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}()
#6 /home/xxx/bots/ChannelTest/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle()
#7 /home/xxx/bots/ChannelTest/vendor/react/promise/src/FulfilledPromise.php(42): React\Promise\Promise::React\Promise\{closure}()....
```

**Comment by bohzio** [comment]
Hi, can you provide the code that throws this error?

**Comment by hamidqp** [comment]
![image](https://user-images.githubusercontent.com/48647106/101090323-b8344a80-35cb-11eb-9a27-a1b44ca8d217.png)

Its Update! when someone tap on the poll that created by robot, telegram will send that update and zanzara shows that cannot process that update included [Poll](https://core.telegram.org/bots/api#poll).

**Comment by cheeghi** [comment]
Release **0.5.2** with the fix. We have also added the polls listener:

```php
<?php

$bot = new Zanzara("TOKEN", $config);

$bot->onPoll(function (Context $ctx) {
    $poll = $ctx->getPoll();
});
```
