### ISSUE TITLE
Telegram connection time out logs

### ISSUE THREAD

**Issue by hamidqp** [badfarm/zanzara#13]
Hi, Im running a bot 2 days and sometimes every minute Get this on logs! how I can get rid of them ?

```
Failed to call Telegram Bot Api, method: getUpdates, params: {
    "offset": 508191280,
    "limit": 100,
    "timeout": 50,
    "allowed_updates": []
}, reason: RuntimeException: Connection to tls://api.telegram.org:443 timed out after 60 seconds in /bot/vendor/react/socket/src/TimeoutConnector.php:41
Stack trace:
#0 /bot/vendor/react/promise/src/RejectedPromise.php(28): React\Socket\TimeoutConnector::React\Socket\{closure}()
#1 /bot/vendor/react/promise/src/Promise.php(134): React\Promise\RejectedPromise->then()
#2 /bot/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}()
#3 /bot/vendor/react/promise/src/Promise.php(148): React\Promise\Promise->settle()
#4 /bot/vendor/react/promise/src/Promise.php(237): React\Promise\Promise->reject()
#5 /bot/vendor/react/promise-timer/src/functions.php(47): React\Promise\Promise::React\Promise\{closure}()
#6 /bot/vendor/react/event-loop/src/Timer/Timers.php(96): React\Promise\Timer\{closure}()
#7 /bot/vendor/react/event-loop/src/StreamSelectLoop.php(184): React\EventLoop\Timer\Timers->tick()
#8 /bot/vendor/badfarm/zanzara/src/Zanzara/Zanzara.php(85): React\EventLoop\StreamSelectLoop->run()
#9 /bot/bot.php(454): Zanzara\Zanzara->run()
#10 {main}
Failed to process Telegram update , reason: TypeError: Argument 1 passed to Zanzara\UpdateMode\Polling::Zanzara\UpdateMode\{closure}() must be an instance of Zanzara\Telegram\Type\Response\TelegramException, instance of RuntimeException given, called in /bot/vendor/react/promise/src/RejectedPromise.php on line 28 and defined in /bot/vendor/badfarm/zanz
ara/src/Zanzara/UpdateMode/Polling.php:83
Stack trace:
#0 /bot/vendor/react/promise/src/RejectedPromise.php(28): Zanzara\UpdateMode\Polling->Zanzara\UpdateMode\{closure}()
#1 /bot/vendor/react/promise/src/Promise.php(134): React\Promise\RejectedPromise->then()
#2 /bot/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}()
#3 /bot/vendor/react/promise/src/Promise.php(148): React\Promise\Promise->settle()
#4 /bot/vendor/react/promise/src/Promise.php(237): React\Promise\Promise->reject()
#5 /bot/vendor/react/promise/src/RejectedPromise.php(42): React\Promise\Promise::React\Promise\{closure}()
#6 /bot/vendor/react/promise/src/Promise.php(135): React\Promise\RejectedPromise->done()
#7 /bot/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}()
#8 /bot/vendor/react/promise/src/Promise.php(148): React\Promise\Promise->settle()
#9 /bot/vendor/react/promise/src/Promise.php(237): React\Promise\Promise->reject()
#10 /bot/vendor/react/promise/src/Deferred.php(43): React\Promise\Promise::React\Promise\{closure}()
#11 /bot/vendor/clue/buzz-react/src/Io/Transaction.php(99): React\Promise\Deferred->reject()
#12 /bot/vendor/react/promise/src/RejectedPromise.php(28): Clue\React\Buzz\Io\Transaction->Clue\React\Buzz\Io\{closure}()
#13 /bot/vendor/react/promise/src/Promise.php(134): React\Promise\RejectedPromise->then()
#14 /bot/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}()
#15 /bot/vendor/react/promise/src/Promise.php(148): React\Promise\Promise->settle()
#16 /bot/vendor/react/promise/src/Promise.php(237): React\Promise\Promise->reject()
#17 /bot/vendor/react/promise/src/RejectedPromise.php(42): React\Promise\Promise::React\Promise\{closure}()
#18 /bot/vendor/react/promise/src/Promise.php(135): React\Promise\RejectedPromise->done()
#19 /bot/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}()
#20 /bot/vendor/react/promise/src/Promise.php(148): React\Promise\Promise->settle()
#21 /bot/vendor/react/promise/src/Promise.php(237): React\Promise\Promise->reject()
#22 /bot/vendor/react/promise/src/RejectedPromise.php(42): React\Promise\Promise::React\Promise\{closure}()
#23 /bot/vendor/react/promise/src/Promise.php(135): React\Promise\RejectedPromise->done()
#24 /bot/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}()
#25 /bot/vendor/react/promise/src/Promise.php(148): React\Promise\Promise->settle()
#26 /bot/vendor/react/promise/src/Promise.php(237): React\Promise\Promise->reject()
#27 /bot/vendor/react/promise/src/Deferred.php(43): React\Promise\Promise::React\Promise\{closure}()
#28 /bot/vendor/clue/buzz-react/src/Io/Sender.php(110): React\Promise\Deferred->reject()
#29 /bot/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): Clue\React\Buzz\Io\Sender->Clue\React\Buzz\Io\{closure}()
#30 /bot/vendor/react/http-client/src/Request.php(203): Evenement\EventEmitter->emit()
#31 /bot/vendor/react/promise/src/RejectedPromise.php(28): React\HttpClient\Request->closeError()
#32 /bot/vendor/react/promise/src/Promise.php(134): React\Promise\RejectedPromise->then()
#33 /bot/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}()
#34 /bot/vendor/react/promise/src/Promise.php(148): React\Promise\Promise->settle()
#35 /bot/vendor/react/promise/src/Promise.php(237): React\Promise\Promise->reject()
#36 /bot/vendor/react/promise/src/RejectedPromise.php(42): React\Promise\Promise::React\Promise\{closure}()
#37 /bot/vendor/react/promise/src/Promise.php(135): React\Promise\RejectedPromise->done()
#38 /bot/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}()
#39 /bot/vendor/react/promise/src/Promise.php(148): React\Promise\Promise->settle()
#40 /bot/vendor/react/promise/src/Promise.php(237): React\Promise\Promise->reject()
#41 /bot/vendor/react/promise-timer/src/functions.php(47): React\Promise\Promise::React\Promise\{closure}()
#42 /bot/vendor/react/event-loop/src/Timer/Timers.php(96): React\Promise\Timer\{closure}()
#43 /bot/vendor/react/event-loop/src/StreamSelectLoop.php(184): React\EventLoop\Timer\Timers->tick()
#44 /bot/vendor/badfarm/zanzara/src/Zanzara/Zanzara.php(85): React\EventLoop\StreamSelectLoop->run()
#45 /bot/bot.php(454): Zanzara\Zanzara->run()
#46 {main}
```

**Comment by cheeghi** [comment]
Hi, the error says your host can't reach the Telegram servers, are you sure there isn't any connection problem on your host?

**Comment by cheeghi** [comment]
Actually seems that Telegram is ignoring the **timeout** param. By default we tell Telegram to keep the connection open for ```50 seconds```, if a new update comes within 50 seconds Telegram returns an array containing the update, we process the update and then we re-open a new connection waiting for new updates. If no updates comes, Telegram after 50 seconds returns an empty array anyway. But in your case Telegram isn't returning the array after 50 seconds (in fact the connection goes in timeout). Anyway, as you said, ```the error doesn't prevent your bot from working correctly```.

**Comment by hamidqp** [comment]
Thanks for the reply and interesting information, but if there was a way to ignore these types of errors it would be great.😅
